In [1]:
import pandas as pd

In [3]:
nhanes = pd.read_csv(
     "../../../examples/nhanes-equity/data/nhanes_equity_v6.csv"
)

print(nhanes.shape)
print(nhanes.columns.tolist())

(105626, 18)
['Cycle', 'BMI', 'Weight', 'Height', 'Waist', 'WeightMEC', 'Strata', 'PSU', 'Gender', 'Race', 'Education', 'Marital', 'Age', 'PIR', 'EducationClean', 'MaritalClean', 'IncomeGroup', 'WHtR']

/tmp/ipykernel_12633/1358711449.py:1: DtypeWarning: Columns (11: Marital, 15: MaritalClean) have mixed types. Specify dtype option on import or set low_memory=False.
  nhanes = pd.read_csv(

In [5]:

nhanes_clean = nhanes.dropna(
    subset=["BMI", "IncomeGroup", "Gender"]
)

print(len(nhanes_clean))

87647

In [6]:
bmi_summary_py = (
    nhanes_clean
    .groupby(["IncomeGroup", "Gender"])["BMI"]
    .agg(["count", "mean", "std"])
    .reset_index()
)

bmi_summary_py

          IncomeGroup  Gender  count       mean       std
0  High Income (>3.5)  Female  11743  25.741674  7.505112
1  High Income (>3.5)    Male  12095  26.105941  6.808015
2   Low Income (<1.3)  Female  16548  25.949257  8.648259
3   Low Income (<1.3)    Male  14847  24.048655  7.170655
4       Middle Income  Female  16432  26.386874  8.200560
5       Middle Income    Male  15982  25.519232  7.217699

In [7]:
from helpers import summarize_bmi

bmi_helper_result = summarize_bmi(nhanes)

bmi_helper_result

          IncomeGroup  Gender  count       mean       std
0  High Income (>3.5)  Female  11743  25.741674  7.505112
1  High Income (>3.5)    Male  12095  26.105941  6.808015
2   Low Income (<1.3)  Female  16548  25.949257  8.648259
3   Low Income (<1.3)    Male  14847  24.048655  7.170655
4       Middle Income  Female  16432  26.386874  8.200560
5       Middle Income    Male  15982  25.519232  7.217699

In [8]:
bmi_summary_py.equals(bmi_helper_result)

True

In [9]:
bmi_summary_rounded_py = bmi_summary_py.copy()

bmi_summary_rounded_py["mean"] = bmi_summary_rounded_py["mean"].round(2)
bmi_summary_rounded_py["std"] = bmi_summary_rounded_py["std"].round(2)

bmi_summary_rounded_py

          IncomeGroup  Gender  count   mean   std
0  High Income (>3.5)  Female  11743  25.74  7.51
1  High Income (>3.5)    Male  12095  26.11  6.81
2   Low Income (<1.3)  Female  16548  25.95  8.65
3   Low Income (<1.3)    Male  14847  24.05  7.17
4       Middle Income  Female  16432  26.39  8.20
5       Middle Income    Male  15982  25.52  7.22